/**
 * The widget layout is compiled into a string and evaluated in a different
 * process, which makes it uniquely easy to break in ways no type checker or
 * render test can see. These tests close that gap by inspecting the compiled
 * source string itself.
 *
 * A failure here means the widget would render fine in development and fail on a
 * device, so treat these as load-bearing rather than cosmetic.
 */

import { parse } from '@babel/parser';
import _traverse from '@babel/traverse';

import BlinkWidget from '@/widgets/BlinkWidget';
import { EMPTY_SNAPSHOT, buildWidgetSnapshot } from '@/features/widget/snapshot';
import type { Task } from '@/lib/types';

// @babel/traverse ships CJS; interop differs between ts-jest and babel-jest.
const traverse = ((_traverse as unknown as { default?: typeof _traverse }).default ??
  _traverse) as typeof _traverse;

/**
 * Names the widget runtime installs on `globalThis`, taken from
 * `expo-widgets/bundle/index.ts` plus the component and modifier sets it spreads
 * in. Anything outside this list is a reference the widget runtime cannot resolve.
 */
const WIDGET_RUNTIME_GLOBALS = new Set([
  // @expo/ui/swift-ui components used by the layout
  'Text',
  'VStack',
  'HStack',
  'ZStack',
  'Spacer',
  'Image',
  'Divider',
  'Gauge',
  'Button',
  'Link',
  'Group',
  // modifiers
  'font',
  'padding',
  'foregroundStyle',
  'foregroundColor',
  'bold',
  'italic',
  'lineLimit',
  'opacity',
  'frame',
  'widgetURL',
  'containerBackground',
  'accessibilityLabel',
  'widgetAccentedRenderingMode',
  'containerShape',
  'clipShape',
  'background',
  'cornerRadius',
  'shadow',
  'tint',
  'multilineTextAlignment',
  // jsx runtime stub
  'jsx',
  'jsxs',
  'jsxDEV',
  '_jsx',
  '_jsxs',
  '_jsxDEV',
  'Fragment',
  '_Fragment',
  'jsxProd',
  '_jsxFileName',
  // react stub
  'React',
  'Children',
  'isValidElement',
  'createContext',
  'useContext',
  // react-native stub
  'PlatformColor',
]);

/** Language built-ins that exist in any JS runtime. */
const JS_BUILTINS = new Set([
  'Object',
  'Array',
  'String',
  'Number',
  'Boolean',
  'Math',
  'Date',
  'JSON',
  'Map',
  'Set',
  'Promise',
  'Error',
  'undefined',
  'NaN',
  'Infinity',
  'parseInt',
  'parseFloat',
  'isNaN',
  'isFinite',
  'console',
  'globalThis',
  'Symbol',
  'RegExp',
  'encodeURIComponent',
  'decodeURIComponent',
]);

/** Every identifier referenced but not declared inside the compiled layout. */
function freeIdentifiers(source: string): string[] {
  const ast = parse(`(${source})`, { sourceType: 'script' });
  const found = new Set<string>();

  traverse(ast, {
    Program(path) {
      for (const name of Object.keys(path.scope.globals)) {
        found.add(name);
      }
    },
  });

  return [...found].sort();
}

function makeTask(overrides: Partial<Task> = {}): Task {
  return {
    id: 't1',
    title: 'Task',
    dueAt: null,
    remindAt: null,
    bucket: 'today',
    status: 'open',
    recurrence: null,
    sortKey: 1024,
    createdAt: Date.now(),
    completedAt: null,
    snoozedUntil: null,
    snoozeCount: 0,
    ...overrides,
  };
}

describe('BlinkWidget compilation', () => {
  it('compiles the widget function into a source string', () => {
    // The babel widgets plugin replaces the default export with a string. If this
    // is a function, the transform did not run and the widget cannot work.
    expect(typeof BlinkWidget).toBe('string');
  });

  it('preserves the function body so the runtime can evaluate it', () => {
    const source = BlinkWidget as unknown as string;
    expect(source).toContain('function');
    expect(source).toContain('widgetFamily');
    expect(source).toContain('THE ONE THING');
  });

  it('removes the widget directive from the extracted source', () => {
    // The directive is consumed during detection. Note that the word 'widget'
    // legitimately survives as the containerBackground placement argument, so
    // assert on the directive position rather than on the word.
    expect(BlinkWidget as unknown as string).not.toMatch(
      /^\s*function[^{]*\{\s*['"]widget['"]\s*;/
    );
  });
});

describe('BlinkWidget extracted source', () => {
  it('is valid JavaScript', () => {
    // This is the invariant that matters most. The layout is generated by
    // @babel/generator in compact mode and then evaluated in the widget runtime,
    // so anything that produces a syntax error here fails silently on a device.
    // Concretely: a `\n` escape inside a string literal is emitted as a real
    // newline, which is invalid JavaScript.
    expect(() => parse(`(${BlinkWidget as unknown as string})`, { sourceType: 'script' })).not.toThrow();
  });

  it('escapes newlines inside string literals', () => {
    // Belt and braces on the same bug class, checked against the AST so that a
    // newline in a comment can never produce a false positive.
    const offenders: string[] = [];
    traverse(parse(`(${BlinkWidget as unknown as string})`, { sourceType: 'script' }), {
      StringLiteral(path) {
        const raw = path.node.extra?.raw;
        if (typeof raw === 'string' && raw.includes('\n')) {
          offenders.push(raw);
        }
      },
    });
    expect(offenders).toEqual([]);
  });
});

describe('BlinkWidget runtime references', () => {
  it('references only globals that the widget runtime provides', () => {
    const free = freeIdentifiers(BlinkWidget as unknown as string);
    const unresolvable = free.filter(
      (name) => !WIDGET_RUNTIME_GLOBALS.has(name) && !JS_BUILTINS.has(name)
    );
    // A hit here is the classic widget bug: a module-scope constant or import
    // referenced inside the layout is undefined in the widget's JS runtime.
    expect(unresolvable).toEqual([]);
  });

  it('does not leak module imports into the compiled layout', () => {
    const source = BlinkWidget as unknown as string;
    expect(source).not.toContain('require(');
    expect(source).not.toMatch(/_swiftUi|_modifiers|_expoWidgets/);
  });

  it('keeps its colours inside the function so they cross the boundary', () => {
    const source = BlinkWidget as unknown as string;
    // These hex values must appear in the source text itself.
    expect(source).toContain('#7C8CFF');
    expect(source).toContain('#0A0D14');
  });
});

describe('BlinkWidget layout behaviour', () => {
  it('has a snapshot shape that survives JSON round-tripping', () => {
    const snapshot = buildWidgetSnapshot([makeTask({ title: 'Ship it' })], Date.now());
    expect(JSON.parse(JSON.stringify(snapshot))).toEqual(snapshot);
  });

  it('keeps the empty snapshot serialisable too', () => {
    expect(JSON.parse(JSON.stringify(EMPTY_SNAPSHOT))).toEqual(EMPTY_SNAPSHOT);
  });
});
